[package]
name = "key-event-serde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "^1.0.0"
toml = "^0.5.8"
tuirealm = { version = "^1.4.0", features = [ "serialize" ] }
