[package]
name = "rand-seed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8"
rand_pcg = "^0.3"
rand_seeder = "^0.2"
