[package]
name = "chrono-tz-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "^0.4"
chrono-tz = "^0.6"
faketime = "0.2.1"
tempfile = "^3.3.0"
